/*
 *
 * Copyright (c) 2018 João Pedro Martins Neves <joao95neves@gmail.com> - All Rights Reserved
 * Unauthorized copying/remixing/sharing of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by João Pedro Martins Neves <joao95neves@gmail.com>, Portugal, CIVIL ID: 14298812
 *
 */

// MergerJS imports:
//
// @import '/enums/environmentType'
// @import '/enums/colors'
// @import '/enums/navbarItemType'
// @import '/enums/navItemID'
// @import '/enums/gridOrientationType'
// @import '/enums/requestType'
// @import '/enums/fiatSymbol'
// @import '/enums/tradingToolsType'
// @import '/models/httpClientResponse'
// @import '/models/changePasswordDTO'
// @import '/models/spreadPricesModel'
// @import '/models/changeModel'
// @import 'constants'
// @import '/services/devErrors'
// $import 'when-dom-ready/dist/index.umd'
// $import 'sweetalert2/dist/sweetalert2.all.min'
// $import 'ccxt/build/ccxt.browser'
// $import 'highcharts/highstock'
// @import '/services/externalLibs'
// @import '/services/utils'
// @import '/services/DOM'
// @import '/services/httpClient'
// @import '/services/exchangeClient'
// @import '/navbar/navbarItemBase'
// @import '/interfaces/pageTemplates'
// @import '/interfaces/modelBase'
// @import '/interfaces/viewBase'
// @import '/interfaces/controllerBase'
// @import '/pages/dashboard/dashboard.templates'
// @import '/pages/dashboard/dashboard.model'
// @import '/pages/dashboard/dashboard.view'
// @import '/pages/dashboard/dashboard.controller'
// @import '/pages/tradeRoom/trade/trade.templates'
// @import '/pages/tradeRoom/trade/trade.model'
// @import '/pages/tradeRoom/trade/trade.view'
// @import '/pages/tradeRoom/trade/trade.controller'
// @import '/pages/tradeRoom/markets/markets.templates'
// @import '/pages/tradeRoom/markets/markets.model'
// @import '/pages/tradeRoom/markets/markets.view'
// @import '/pages/tradeRoom/markets/markets.controller'
// @import '/pages/tradeRoom/tradeRoom.templates'
// @import '/pages/tradeRoom/tradeRoom.model'
// @import '/pages/tradeRoom/tradeRoom.view'
// @import '/pages/tradeRoom/tradeRoom.controller'
// @import '/pages/settings/settings.templates'
// @import '/pages/settings/settings.model'
// @import '/pages/settings/settings.view'
// @import '/pages/settings/settings.controller'
// @import '/navbar/navbar.templates'
// @import '/navbar/navbar.model'
// @import '/navbar/navbar.view'
// @import '/navbar/navbar.controller'
// @import '/enums/themeType'
// @import '/services/themes'
// @import 'trader.main'
// @import '/services/traderRoutes'
'use strict';
