CREATE TABLE dbo.AuditLog
(
    Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL FOREIGN KEY REFERENCES dbo.ApplicationUser(Id),
    EventTypeId TINYINT NOT NULL,
    LogDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UserIP NVARCHAR(15) NOT NULL
)
